image:
  file: .gitpod.Dockerfile

tasks:
  # Install dependencies
  - name: Install dependencies
    init: make update

  # Initialize app config
  - name: Generate app config
    env:
      PORT: 4040
    init: go run ./dev-setup/setup.go

  # Run the project
  - name: Run project
    command: make watch

ports:
  - port: 4040
    visibility: public
    onOpen: notify

jetbrains:
  goland:
    plugins:
      - mobi.hsz.idea.gitignore
      - ru.adelf.idea.dotenv
      - com.ypwang.plugin.go-linter