run:
  concurrency: 3
  timeout: 2m
  tests: false
  print-resources-usage: true

  skip-dirs:
    - template
    - .idea

  skip-files:
    - Makefile
    - Dockerfile
    - .env.example
    - .env
    - .air.toml

linters:
  enable:
    - errcheck
    - unparam
    - unused
    - structcheck
    - deadcode

  disable:
    - gochecknoglobals # TODO: need to move to enable after refactoring the current global variables
    - gochecknoinits # TODO: need to move to enable after refactoring the current init functions